---

- hosts: all
  roles:
  - create-file

- hosts: worker_01
  roles:
  - create-a-file

  handlers:
  - name: Print message
    debug:
      msg: "All done"
    when: fileName == "c"

- hosts: worker_02
  roles:
  - create-a-file

  handlers:
  - name: Print message
    debug:
      msg: "All done"
    when: fileName == "c"

- hosts: worker_03
  roles:
  - create-a-file

  handlers:
  - name: Print message
    debug:
      msg: "All done"
    when: fileName == "c"


