services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  server:
    build: 
      context: ./server
    ports:
      - 5000:5000
    depends_on:
      - mongo
  client:
    build: 
      context: ./client
    ports:
      - 3000:80
    depends_on:
      - server