services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  server:
    build: 
      context: ./server
      # for local development
      # dockerfile: dev.Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 5000:5000
    # environment:
    #    - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo
  client:
    environment:
      - VITE_MY_NODE_NAME=worker-node-01
      - VITE_HOSTNAME=myapp-deployment-5bb489b479-sbrms
    build: 
      context: ./client
      # for local development
      # dockerfile: dev.Dockerfile
      args:
        MODE: production
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:80
    depends_on:
      - server