# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: default
  labels:
    app.kubernetes.io/name: load-balancer-example
spec:
  externalIPs:
  - 192.168.0.194
  selector:
    app.kubernetes.io/name: load-balancer-example
  type: LoadBalancer
  ports:
  - name: nginx
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:2.0
        name: hello-world
        ports:
        - containerPort: 80
