# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-production
  namespace: default
data:
  env.production: |
    VITE_FIRST_NAME=prod {{ .Values.appName }}
    VITE_LAST_NAME=prod {{ .Values.appName }}
