# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment-v0.0.1
  namespace: default
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "cheulong/task-list-app:frontend-0.0.4"
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 500m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 10Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: envproduction
          mountPath: /env.production
      volumes:
        - name: envproduction
          configMap:
            name: {{ .Values.appName }}-production
