# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: default
spec:
  selector:
    app: {{ .Values.appName }}
  type: NodePort
  ports:
  -  port: 8082
     targetPort: 80
     nodePort: 30171
