---

- hosts: all
  vars_files:
    - my_vars.yaml
  roles:
  - create-file
  tasks:
    - debug:
        msg: "{{ var_from_vars_file }}"
      when: var_from_vars_file is defined

- hosts: worker_01
  roles:
  - create-a-file

  handlers:
  - name: Print message
    debug:
      msg: "All done"
    when: file_name == "c"

- hosts: worker_02
  roles:
  - create-a-file

  handlers:
  - name: Print message
    debug:
      msg: "All done"
    when: file_name == "c"

- hosts: worker_03
  roles:
  - create-a-file

  handlers:
  - name: Print message
    debug:
      msg: "All done"
    when: file_name == "c"


